// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function C(arg1) {
  return window['go']['main']['App']['C'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
